theme = "ayu_mirage"

[editor]
bufferline = "multiple"
shell = ["fish", "-c"]

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false

[keys.normal]
"C-y" = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ":set mouse false", ":set mouse true"
] # yazi in helix

"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "select_mode",
  "goto_line_start",
  "normal_mode",
] # Move line(s) down

"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "flip_selections",
] # Move line(s) up
