theme = "ayu_mirage"

[editor]
bufferline = "multiple"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
