theme = "ayu_mirage"

[editor]
bufferline = "multiple"
shell = ["fish", "-c"]

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = true
