[language-server.tinymist]
command = "tinymist"
config = { preview.background.enabled = true, preview.background.args = ["--data-plane-host=127.0.0.1:23635", "--invert-colors=never", "--open"] }

[[language]]
name = "typst"
language-servers = ["tinymist"]

[[language]]
name = "python"
language-servers = ["ty", "ruff"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ty.config]
inlayHints.callArgumentNames = false
experimental.rename = true
experimental.autoImport = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer]
command = "rust-analyzer"
